background #131318
foreground #e4e1e9
cursor #e4e1e9
cursor_text_color #131318
selection_background #918f9a
selection_foreground #e4e1e9
color0 #131318
color1 #ffb4ab
color2 #bfc2ff
color3 #e8b9d5
color4 #c5c4dd
color5 #bfc2ff
color6 #e8b9d5
color7 #e4e1e9
color8 #918f9a
color9 #ffb4ab
color10 #bfc2ff
color11 #e8b9d5
color12 #c5c4dd
color13 #bfc2ff
color14 #918f9a
color15 #e0e0ff
