-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { border_size = 1 },
  decoration = { rounding = 7, glow = { enabled = true, range = 22, color = "rgb(CBBFD3)" } },
  input = { kb_layout = "us", kb_variant = "", kb_options = "", sensitivity = -0.21, accel_profile = "flat", touchpad = { natural_scroll = true, scroll_factor = 0.8 } },
})

do
  local ok, wc = pcall(dofile, os.getenv("HOME") .. "/.cache/ryoku/hypr-colors.lua")
  local function rgb(h, f) if type(h) ~= "string" then h = f end return "rgb(" .. h:gsub("#", "") .. ")" end
  hl.config({ general = { ["col.active_border"] = { colors = { rgb(ok and wc and wc.active, "#e0563b"), rgb(ok and wc and wc.inactive, "#313a4d") }, angle = 45 } } })
end
hl.animation({ leaf = "borderangle", enabled = true, speed = 80.0, bezier = "linear", style = "loop" })
hl.gesture({ fingers = 4, direction = "horizontal", action = "workspace" })

hl.env("XCURSOR_THEME", "Bibata-Modern-Amber")
hl.env("XCURSOR_SIZE", "15")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Amber")
hl.env("HYPRCURSOR_SIZE", "15")

local function ryoku_plugin_loaded(name)
  for _, p in ipairs(hl.get_loaded_plugins()) do
    if p.name == name then return true end
  end
  return false
end

pcall(function()
  hl.plugin.load("/usr/lib/hyprland/plugins/hyprglass.so")
  if ryoku_plugin_loaded("hyprglass") then
    hl.config({ plugin = { hyprglass = { enabled = 1, default_preset = "glass", blur_strength = 5.0, glass_opacity = 1.0, tint_color = 0x8899aa22, brightness = 0.86, default_theme = "dark" } } })
  end
end)


hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Amber 15")
end)
